version: "3.7"

services:
  double-check-api-database:
    container_name: double-check-api-database
    image: dev-vivo.servehttp.com:5000/double-check-api-database:master
    ports:
      - 3307:3306
    volumes:
      - ../double-check-api/db:/var/lib/mysql
    networks:
      - gateway
    environment:
      MYSQL_USER: double-check-api
      MYSQL_PASSWORD: double-check-api
      MYSQL_DATABASE: double-check-api
      MYSQL_ROOT_PASSWORD: "123"
    command: --innodb_use_native_aio=0 --socket=/tmp/mysql.sock --bind_address=0.0.0.0



  double-check-api:
    container_name: double-check-api
    image: dev-vivo.servehttp.com:5000/double-check-api:master
    env_file: ../double-check-api/.env.dev
    depends_on:
      - double-check-api-database
    ports:
      - 3333:3333
    volumes: 
      - "../double-check-api:/app"
    networks:
      - gateway
    environment:
      - ENVIRONMENT=DEVELOPMENT
    command: sh -c "npm install && npm run dev"


  zeus-service-database:
    container_name: zeus-service-database
    image: dev-vivo.servehttp.com:5000/zeus-service-database:master
    ports:
      - 3308:3306
    volumes:
      - ../zeus-service/db:/var/lib/mysql
    networks:
      - gateway
    environment:
      MYSQL_USER: zeus-service
      MYSQL_PASSWORD: zeus-service
      MYSQL_DATABASE: zeus-service
      MYSQL_ROOT_PASSWORD: "123"
    command: --innodb_use_native_aio=0 --socket=/tmp/mysql.sock --bind_address=0.0.0.0


  zeus-service:
    container_name: zeus-service
    image: dev-vivo.servehttp.com:5000/zeus-service:master
    env_file: ../zeus-service/.env.dev
    depends_on:
      - zeus-service-database
    ports:
      - 3001:3001
    volumes:
      - "../zeus-service:/app"
      - "../zeus-service/base:/app/base"
    networks:
      - gateway
    environment:
      - ENVIRONMENT=DEVELOPMENT
    command: sh -c "npm install && npm run dev"

  
  double-check-app:
    container_name: double-check-app
    image: dev-vivo.servehttp.com:5000/double-check-app:master
    ports:
      - 3000:3000
    env_file: ../double-check-app/.env.dev
    environment:
      - ENVIRONMENT=DEVELOPMENT
    volumes: 
      - ../double-check-app:/app
    networks:
      - gateway
    command: npm run dev


networks:
  gateway:
    driver: bridge